In [136]:
import pandas as pd
import numpy as np

In [137]:
import pandas as pd

df = pd.read_csv("../data/raw/players_data_light-2025_2026.csv")

In [138]:
df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25.0,2000.0,34,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20.0,2006.0,21,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,26.0,1999.0,8,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26.0,1999.0,13,11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
df.shape

(2779, 53)

In [140]:
df.columns.tolist()

['Rk',
 'Player',
 'Nation',
 'Pos',
 'Squad',
 'Comp',
 'Age',
 'Born',
 'MP',
 'Starts',
 'Min',
 '90s',
 'Gls',
 'Ast',
 'G+A',
 'G-PK',
 'PK',
 'PKatt',
 'CrdY',
 'CrdR',
 'G+A-PK',
 'Sh',
 'SoT',
 'SoT%',
 'Sh/90',
 'SoT/90',
 'G/Sh',
 'G/SoT',
 'PK_stats_shooting',
 'PKatt_stats_shooting',
 'Crs',
 'TklW',
 'Int',
 'Fld',
 'CrdY_stats_misc',
 'CrdR_stats_misc',
 '2CrdY',
 'Fls',
 'OG',
 'GA',
 'GA90',
 'SoTA',
 'Saves',
 'Save%',
 'W',
 'D',
 'L',
 'CS',
 'CS%',
 'PKatt_stats_keeper',
 'PKA',
 'PKsv',
 'PKm']

In [141]:
df["Pos"].unique()

array(['MF,FW', 'DF', 'MF', 'MF,DF', 'FW,MF', 'DF,MF', 'FW', 'GK',
       'DF,FW', nan], dtype=object)

In [142]:
df = df[df["Min"] > 500]

In [143]:
df.shape

(1881, 53)

In [144]:
for pos in df["Pos"].unique():
    print(pos)

MF,FW
MF
MF,DF
FW,MF
DF,MF
DF
FW
GK

In [145]:
forwards = df[df["Pos"].str.contains("FW", na=False)]

forwards.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25.0,2000.0,34,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20.0,2006.0,21,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,Matthis Abline,fr FRA,"FW,MF",Nantes,fr Ligue 1,23.0,2003.0,32,27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,Giorgi Abuashvili,ge GEO,"MF,FW",Metz,fr Ligue 1,23.0,2003.0,21,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,Ragnar Ache,de GER,FW,Köln,de Bundesliga,27.0,1998.0,29,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
striker_features = [
    "Gls",
    "Ast",
    "G+A",
    "Sh",
    "SoT",
    "G/Sh"
]

In [147]:
forwards_data = forwards[
    ["Player", "Squad", "Comp"] + striker_features
]

forwards_data.head()

,Player,Squad,Comp,Gls,Ast,G+A,Sh,SoT,G/Sh
0,Brenden Aaronson,Leeds United,eng Premier League,4,5,9,43,16,0.09
2,Jones El-Abdellaoui,Celta Vigo,es La Liga,2,0,2,17,4,0.12
10,Matthis Abline,Nantes,fr Ligue 1,6,4,10,84,22,0.07
16,Giorgi Abuashvili,Metz,fr Ligue 1,2,0,2,17,7,0.12
19,Ragnar Ache,Köln,de Bundesliga,7,4,11,52,22,0.13

In [148]:
df["Pos"].value_counts()

Pos
MF       578
DF       495
FW       183
MF,FW    182
GK       131
DF,MF    113
FW,MF    104
MF,DF     95
Name: count, dtype: int64

In [149]:
strikers = df[df["Pos"] == "FW"]

strikers.shape

(183, 53)

In [150]:
strikers.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Save%,W,D,L,CS,CS%,PKatt_stats_keeper,PKA,PKsv,PKm
19,20,Ragnar Ache,de GER,FW,Köln,de Bundesliga,27.0,1998.0,29,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,Akor Adams,ng NGA,FW,Sevilla,es La Liga,26.0,2000.0,28,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,Che Adams,sct SCO,FW,Torino,it Serie A,29.0,1996.0,31,19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,59,Ludovic Ajorque,fr FRA,FW,Brest,fr Ligue 1,32.0,1994.0,29,29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,76,Alexandre Alemão,br BRA,FW,Rayo Vallecano,es La Liga,28.0,1998.0,22,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
striker_features = [
    "Gls",
    "Ast",
    "G+A",
    "Sh",
    "SoT",
    "G/Sh"
]

In [152]:
striker_data = strikers[
    ["Player", "Squad", "Comp"] + striker_features
]

striker_data.head()

,Player,Squad,Comp,Gls,Ast,G+A,Sh,SoT,G/Sh
19,Ragnar Ache,Köln,de Bundesliga,7,4,11,52,22,0.13
21,Akor Adams,Sevilla,es La Liga,8,3,11,55,27,0.09
22,Che Adams,Torino,it Serie A,5,2,7,48,14,0.10
58,Ludovic Ajorque,Brest,fr Ligue 1,7,9,16,47,15,0.15
75,Alexandre Alemão,Rayo Vallecano,es La Liga,2,0,2,19,9,0.11

In [153]:
sorted(df["Squad"].unique())

['Alavés',
 'Angers',
 'Arsenal',
 'Aston Villa',
 'Atalanta',
 'Athletic Club',
 'Atlético Madrid',
 'Augsburg',
 'Auxerre',
 'Barcelona',
 'Bayern Munich',
 'Bologna',
 'Bournemouth',
 'Brentford',
 'Brest',
 'Brighton',
 'Burnley',
 'Cagliari',
 'Celta Vigo',
 'Chelsea',
 'Como',
 'Cremonese',
 'Crystal Palace',
 'Dortmund',
 'Eintracht Frankfurt',
 'Elche',
 'Espanyol',
 'Everton',
 'Fiorentina',
 'Freiburg',
 'Fulham',
 'Genoa',
 'Getafe',
 'Girona',
 'Gladbach',
 'Hamburger SV',
 'Heidenheim',
 'Hellas Verona',
 'Hoffenheim',
 'Inter',
 'Juventus',
 'Köln',
 'Lazio',
 'Le Havre',
 'Lecce',
 'Leeds United',
 'Lens',
 'Levante',
 'Leverkusen',
 'Lille',
 'Liverpool',
 'Lorient',
 'Lyon',
 'Mainz 05',
 'Mallorca',
 'Manchester City',
 'Manchester Utd',
 'Marseille',
 'Metz',
 'Milan',
 'Monaco',
 'Nantes',
 'Napoli',
 'Newcastle United',
 'Nice',
 'Nottingham Forest',
 'Osasuna',
 'Oviedo',
 'Paris FC',
 'Paris Saint-Germain',
 'Parma',
 'Pisa',
 'RB Leipzig',
 'Rayo Vallecano',
 'Real Betis',
 'Real Madrid',
 'Real Sociedad',
 'Rennes',
 'Roma',
 'Sassuolo',
 'Sevilla',
 'St Pauli',
 'Strasbourg',
 'Stuttgart',
 'Sunderland',
 'Torino',
 'Tottenham Hotspur',
 'Toulouse',
 'Udinese',
 'Union Berlin',
 'Valencia',
 'Villarreal',
 'Werder Bremen',
 'West Ham United',
 'Wolfsburg',
 'Wolves']

In [154]:
ucl_teams = [
    "Arsenal",
    "Aston Villa",
    "Barcelona",
    "Bayern Munich",
    "Dortmund",
    "Chelsea",
    "Eintracht Frankfurt",
    "Inter",
    "Juventus",
    "Leverkusen",
    "Liverpool",
    "Manchester City",
    "Marseille",
    "Milan",
    "Monaco",
    "Napoli",
    "Newcastle United",
    "Paris Saint-Germain",
    "RB Leipzig",
    "Real Madrid",
    "Tottenham Hotspur",
    "Union Berlin",
    "Villarreal"
]

In [155]:
df["is_ucl_team"] = df["Squad"].isin(ucl_teams)

In [156]:
df[["Player", "Squad", "is_ucl_team"]].head(20)

                 Player         Squad  is_ucl_team
0      Brenden Aaronson  Leeds United        False
2   Jones El-Abdellaoui    Celta Vigo        False
4         Himad Abdelli        Angers        False
5              Ali Abdi          Nice        False
6     Salis Abdul Samed          Nice        False
7       Saud Abdulhamid          Lens        False
9       Laurent Abergel       Lorient        False
10       Matthis Abline        Nantes        False
11                Abner          Lyon        False
12    Zakaria Aboukhlal        Torino        False
13          Abdel Abqar        Getafe        False
15          Francis Abu      Toulouse        False
16    Giorgi Abuashvili          Metz        False
18     Francesco Acerbi         Inter         True
19          Ragnar Ache          Köln        False
20    Joshua Acheampong       Chelsea         True
21           Akor Adams       Sevilla        False
22            Che Adams        Torino        False
23          Tyler Adams   Bournemouth        False
25     Tosin Adarabioyo       Chelsea         True

In [157]:
import pandas as pd

df = pd.read_csv("../data/raw/players_data_light-2025_2026.csv")

df = df[df["Min"] > 500].copy()

ucl_teams = [
    "Arsenal", "Aston Villa", "Barcelona", "Bayern Munich", "Dortmund",
    "Chelsea", "Eintracht Frankfurt", "Inter", "Juventus", "Leverkusen",
    "Liverpool", "Manchester City", "Marseille", "Milan", "Monaco",
    "Napoli", "Newcastle United", "Paris Saint-Germain", "RB Leipzig",
    "Real Madrid", "Tottenham Hotspur", "Union Berlin", "Villarreal"
]

df["is_ucl_team"] = df["Squad"].isin(ucl_teams)

striker_features = ["Gls", "Ast", "G+A", "Sh", "SoT", "G/Sh"]

strikers = df[df["Pos"] == "FW"].copy()

striker_data = strikers[
    ["Player", "Squad", "Comp", "is_ucl_team"] + striker_features
]

striker_data.head()

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
19,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13
21,Akor Adams,Sevilla,es La Liga,False,8,3,11,55,27,0.09
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10
58,Ludovic Ajorque,Brest,fr Ligue 1,False,7,9,16,47,15,0.15
75,Alexandre Alemão,Rayo Vallecano,es La Liga,False,2,0,2,19,9,0.11

In [158]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

In [159]:
X = striker_data[striker_features]

In [160]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [161]:
model = NearestNeighbors(
    n_neighbors=6,
    metric="euclidean"
)

model.fit(X_scaled)

NearestNeighbors(metric='euclidean', n_neighbors=6)

In [162]:
striker_data.iloc[0]

Player           Ragnar Ache
Squad                   Köln
Comp           de Bundesliga
is_ucl_team            False
Gls                        7
Ast                        4
G+A                       11
Sh                        52
SoT                       22
G/Sh                    0.13
Name: 19, dtype: object

In [163]:
player_index = 0

distances, indices = model.kneighbors(
    [X_scaled[player_index]]
)

print(indices)

[[  0   5  55 138  98  40]]

In [164]:
similar_players = striker_data.iloc[indices[0]]

similar_players

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
19,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13
92,Julián Álvarez,Atlético Madrid,es La Liga,False,8,4,12,54,26,0.11
812,Francesco Esposito,Inter,it Serie A,True,6,3,9,55,22,0.11
2108,Christian Pulisic,Milan,it Serie A,True,8,3,11,50,24,0.16
1435,Rafael Leão,Milan,it Serie A,True,9,3,12,60,23,0.12
623,Jonathan David,Juventus,it Serie A,True,6,4,10,41,16,0.15

In [165]:
ucl_teams = [
    "Arsenal",
    "Athletic Club",
    "Atlético Madrid",
    "Atalanta",
    "Barcelona",
    "Bayern Munich",
    "Chelsea",
    "Dortmund",
    "Eintracht Frankfurt",
    "Inter",
    "Juventus",
    "Leverkusen",
    "Liverpool",
    "Manchester City",
    "Marseille",
    "Monaco",
    "Napoli",
    "Newcastle United",
    "Paris Saint-Germain",
    "Real Madrid",
    "Tottenham Hotspur",
    "Villarreal"
]

df["is_ucl_team"] = df["Squad"].isin(ucl_teams)

strikers = df[df["Pos"] == "FW"].copy()

striker_data = strikers[
    ["Player", "Squad", "Comp", "is_ucl_team"] + striker_features
]

striker_data.head()

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
19,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13
21,Akor Adams,Sevilla,es La Liga,False,8,3,11,55,27,0.09
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10
58,Ludovic Ajorque,Brest,fr Ligue 1,False,7,9,16,47,15,0.15
75,Alexandre Alemão,Rayo Vallecano,es La Liga,False,2,0,2,19,9,0.11

In [166]:
striker_data[
    striker_data["Player"].isin(
        ["Julián Alvarez", "Christian Pulisic", "Rafael Leão"]
    )
]

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
1435,Rafael Leão,Milan,it Serie A,False,9,3,12,60,23,0.12
2108,Christian Pulisic,Milan,it Serie A,False,8,3,11,50,24,0.16

In [167]:
ucl_strikers = striker_data[
    striker_data["is_ucl_team"] == True
]

ucl_strikers.head(20)

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
92,Julián Álvarez,Atlético Madrid,es La Liga,True,8,4,12,54,26,0.11
168,Pierre-Emerick Aubameyang,Marseille,fr Ligue 1,True,9,5,14,52,28,0.17
209,Folarin Balogun,Monaco,fr Ligue 1,True,13,4,17,71,31,0.14
218,Bradley Barcola,Paris Saint-Germain,fr Ligue 1,True,10,1,11,63,28,0.16
306,Mika Biereth,Monaco,fr Ligue 1,True,2,2,4,19,7,0.11
343,Ange-Yoan Bonny,Inter,it Serie A,True,5,3,8,21,9,0.24
400,Jonathan Burkardt,Eintracht Frankfurt,de Bundesliga,True,11,1,12,38,19,0.24
623,Jonathan David,Juventus,it Serie A,True,6,4,10,41,16,0.15
642,Liam Delap,Chelsea,eng Premier League,True,1,0,1,35,11,0.03
647,Ousmane Dembélé,Paris Saint-Germain,fr Ligue 1,True,10,6,16,43,17,0.19
784,Hugo Ekitike,Liverpool,eng Premier League,True,11,4,15,65,19,0.17
812,Francesco Esposito,Inter,it Serie A,True,6,3,9,55,22,0.11
932,Gonzalo García,Real Madrid,es La Liga,True,4,1,5,16,9,0.25
1004,Anthony Gordon,Newcastle United,eng Premier League,True,6,2,8,48,20,0.06
1026,Antoine Griezmann,Atlético Madrid,es La Liga,True,7,2,9,38,21,0.18
1059,Serhou Guirassy,Dortmund,de Bundesliga,True,16,1,17,76,35,0.20
1068,Gorka Guruzeta,Athletic Club,es La Liga,True,9,3,12,70,28,0.11
1074,Viktor Gyökeres,Arsenal,eng Premier League,True,14,1,15,52,22,0.21
1075,Erling Haaland,Manchester City,eng Premier League,True,25,7,32,119,54,0.18
1167,Rasmus Højlund,Napoli,it Serie A,True,10,3,13,56,22,0.16

In [168]:
striker_data[
    striker_data["Player"].str.contains("Alvarez", case=False, na=False)
]

Empty DataFrame
Columns: [Player, Squad, Comp, is_ucl_team, Gls, Ast, G+A, Sh, SoT, G/Sh]
Index: []

In [169]:
player_name = "Julián Álvarez"

In [170]:
player_name = "NOME_ESATTO"

In [171]:
search_name = "alvarez"

matches = striker_data[
    striker_data["Player"].str.contains(search_name, case=False, na=False)
]

matches

Empty DataFrame
Columns: [Player, Squad, Comp, is_ucl_team, Gls, Ast, G+A, Sh, SoT, G/Sh]
Index: []

In [172]:
search_name = "lvarez"

matches = striker_data[
    striker_data["Player"].str.contains(search_name, case=False, na=False)
]

matches

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
92,Julián Álvarez,Atlético Madrid,es La Liga,True,8,4,12,54,26,0.11

In [173]:
player_name = "Julián Álvarez"

player_index = striker_data[
    striker_data["Player"] == player_name
].index[0]

distances, indices = model.kneighbors(
    [X_scaled[player_index]]
)

similar_players = striker_data.iloc[indices[0]]

similar_players

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
1342,Christian Kofane,Leverkusen,de Bundesliga,True,5,3,8,45,19,0.11
812,Francesco Esposito,Inter,it Serie A,True,6,3,9,55,22,0.11
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15

In [174]:
hidden_targets = similar_players[
    similar_players["is_ucl_team"] == False
]

hidden_targets

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15

In [175]:
similar_players = striker_data.iloc[indices[0]].copy()
similar_players["distance"] = distances[0]

similar_players

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,distance
1342,Christian Kofane,Leverkusen,de Bundesliga,True,5,3,8,45,19,0.11,0.000000
812,Francesco Esposito,Inter,it Serie A,True,6,3,9,55,22,0.11,0.593674
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12,0.688143
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10,0.807440
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09,0.838900
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15,0.907960

In [176]:
similar_players = striker_data.iloc[indices[0]].copy()
similar_players["distance"] = distances[0]

similar_players

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,distance
1342,Christian Kofane,Leverkusen,de Bundesliga,True,5,3,8,45,19,0.11,0.000000
812,Francesco Esposito,Inter,it Serie A,True,6,3,9,55,22,0.11,0.593674
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12,0.688143
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10,0.807440
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09,0.838900
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15,0.907960

In [177]:
def find_similar_non_ucl_players(player_name, n_neighbors=10):
    player_match = striker_data[striker_data["Player"] == player_name]
    
    if player_match.empty:
        return f"Player '{player_name}' not found."
    
    player_index = player_match.index[0]
    
    distances, indices = model.kneighbors(
        [X_scaled[player_index]],
        n_neighbors=n_neighbors
    )
    
    similar_players = striker_data.iloc[indices[0]].copy()
    similar_players["distance"] = distances[0]
    
    hidden_targets = similar_players[
        similar_players["is_ucl_team"] == False
    ].copy()
    
    return hidden_targets

In [178]:
find_similar_non_ucl_players("Julián Álvarez")

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,distance
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12,0.688143
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10,0.807440
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09,0.838900
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15,0.907960
485,Santiago Castro,Bologna,it Serie A,False,7,2,9,58,19,0.12,0.942787
1091,Conrad Harder,RB Leipzig,de Bundesliga,False,3,3,6,39,12,0.08,1.026439

In [179]:
similar_players = striker_data.iloc[indices[0]].copy()
similar_players["distance"] = distances[0]

similar_players["similarity_score"] = 100 / (1 + similar_players["distance"])

hidden_targets = similar_players[
    similar_players["is_ucl_team"] == False
].copy()

hidden_targets.sort_values("similarity_score", ascending=False)

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,distance,similarity_score
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12,0.688143,59.236696
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10,0.807440,55.326870
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09,0.838900,54.380343
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15,0.907960,52.412012

In [180]:
def find_similar_non_ucl_players(player_name, n_neighbors=10):
    player_match = striker_data[striker_data["Player"] == player_name]
    
    if player_match.empty:
        return f"Player '{player_name}' not found."
    
    player_index = player_match.index[0]
    
    distances, indices = model.kneighbors(
        [X_scaled[player_index]],
        n_neighbors=n_neighbors
    )
    
    similar_players = striker_data.iloc[indices[0]].copy()
    similar_players["distance"] = distances[0]
    similar_players["similarity_score"] = 100 / (1 + similar_players["distance"])
    
    hidden_targets = similar_players[
        similar_players["is_ucl_team"] == False
    ].copy()
    
    return hidden_targets.sort_values("similarity_score", ascending=False)

In [181]:
find_similar_non_ucl_players("Julián Álvarez", n_neighbors=15)

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,distance,similarity_score
801,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12,0.688143,59.236696
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10,0.807440,55.326870
858,Roberto Férnandez,Espanyol,es La Liga,False,6,2,8,55,21,0.09,0.838900,54.380343
823,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15,0.907960,52.412012
485,Santiago Castro,Bologna,it Serie A,False,7,2,9,58,19,0.12,0.942787,51.472449
1091,Conrad Harder,RB Leipzig,de Bundesliga,False,3,3,6,39,12,0.08,1.026439,49.347657
19,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13,1.037259,49.085571
1447,Tim Lemperle,Hoffenheim,de Bundesliga,False,8,2,10,50,20,0.14,1.060998,48.520174
1226,Igor Jesus,Nottingham Forest,eng Premier League,False,6,4,10,62,17,0.08,1.144031,46.641117
1195,Gustav Isaksen,Lazio,it Serie A,False,5,1,6,45,17,0.11,1.233321,44.776357
2108,Christian Pulisic,Milan,it Serie A,False,8,3,11,50,24,0.16,1.246479,44.514096

In [182]:
striker_data["Gls_per90"] = striker_data["Gls"] / strikers["90s"]
striker_data["Ast_per90"] = striker_data["Ast"] / strikers["90s"]
striker_data["Sh_per90"] = striker_data["Sh"] / strikers["90s"]
striker_data["SoT_per90"] = striker_data["SoT"] / strikers["90s"]

/var/folders/_8/qqgpg5s56xx_2zs0xs7zbndh0000gp/T/ipykernel_3795/3713893788.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  striker_data["Gls_per90"] = striker_data["Gls"] / strikers["90s"]
/var/folders/_8/qqgpg5s56xx_2zs0xs7zbndh0000gp/T/ipykernel_3795/3713893788.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  striker_data["Ast_per90"] = striker_data["Ast"] / strikers["90s"]
/var/folders/_8/qqgpg5s56xx_2zs0xs7zbndh0000gp/T/ipykernel_3795/3713893788.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  striker_data["Sh_per90"] = striker_data["Sh"] / strikers["90s"]
/var/folders/_8/qqgpg5s56xx_2zs0xs7zbndh0000gp/T/ipykernel_3795/3713893788.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  striker_data["SoT_per90"] = striker_data["SoT"] / strikers["90s"]

In [183]:
striker_data.head()

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90
19,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832
21,Akor Adams,Sevilla,es La Liga,False,8,3,11,55,27,0.09,0.390244,0.146341,2.682927,1.317073
22,Che Adams,Torino,it Serie A,False,5,2,7,48,14,0.10,0.246305,0.098522,2.364532,0.689655
58,Ludovic Ajorque,Brest,fr Ligue 1,False,7,9,16,47,15,0.15,0.247350,0.318021,1.660777,0.530035
75,Alexandre Alemão,Rayo Vallecano,es La Liga,False,2,0,2,19,9,0.11,0.185185,0.000000,1.759259,0.833333

In [184]:
advanced_striker_features = [
    "Gls_per90",
    "Ast_per90",
    "Sh_per90",
    "SoT_per90",
    "G/Sh"
]

In [185]:
X = striker_data[advanced_striker_features]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

model = NearestNeighbors(
    n_neighbors=10,
    metric="euclidean"
)

model.fit(X_scaled)

NearestNeighbors(metric='euclidean', n_neighbors=10)

In [186]:
find_similar_non_ucl_players("Julián Álvarez")

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90,distance,similarity_score
847,Evan Ferguson,Roma,it Serie A,False,3,2,5,27,15,0.11,0.348837,0.232558,3.139535,1.744186,0.863320,53.667654
191,Cédric Bakambu,Real Betis,es La Liga,False,3,1,4,21,9,0.14,0.517241,0.172414,3.620690,1.551724,1.013284,49.670101
2108,Christian Pulisic,Milan,it Serie A,False,8,3,11,50,24,0.16,0.465116,0.174419,2.906977,1.395349,1.293830,43.595217
1435,Rafael Leão,Milan,it Serie A,False,9,3,12,60,23,0.12,0.456853,0.152284,3.045685,1.167513,1.314081,43.213697
1091,Conrad Harder,RB Leipzig,de Bundesliga,False,3,3,6,39,12,0.08,0.312500,0.312500,4.062500,1.250000,1.364877,42.285502
19,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832,1.366291,42.260226

In [187]:
df = df[
    (df["MP"] >= 15) &
    (df["Min"] >= 900)
].copy()

In [188]:
strikers = df[df["Pos"] == "FW"].copy()

striker_data = strikers[
    ["Player", "Squad", "Comp", "is_ucl_team"] + striker_features
].copy()

striker_data["Gls_per90"] = striker_data["Gls"] / strikers["90s"]
striker_data["Ast_per90"] = striker_data["Ast"] / strikers["90s"]
striker_data["Sh_per90"] = striker_data["Sh"] / strikers["90s"]
striker_data["SoT_per90"] = striker_data["SoT"] / strikers["90s"]

advanced_striker_features = [
    "Gls_per90",
    "Ast_per90",
    "Sh_per90",
    "SoT_per90",
    "G/Sh"
]

striker_data = striker_data.reset_index(drop=True)

In [189]:
X = striker_data[advanced_striker_features]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

model = NearestNeighbors(
    n_neighbors=10,
    metric="euclidean"
)

model.fit(X_scaled)

NearestNeighbors(metric='euclidean', n_neighbors=10)

In [190]:
find_similar_non_ucl_players("Julián Álvarez")

,Player,Squad,Comp,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90,distance,similarity_score
0,Ragnar Ache,Köln,de Bundesliga,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832,0.503260,66.522074
1,Akor Adams,Sevilla,es La Liga,False,8,3,11,55,27,0.09,0.390244,0.146341,2.682927,1.317073,0.635584,61.140245
107,Rômulo,RB Leipzig,de Bundesliga,False,9,4,13,61,27,0.15,0.389610,0.173160,2.640693,1.168831,0.732426,57.722507
73,Rafael Leão,Milan,it Serie A,False,9,3,12,60,23,0.12,0.456853,0.152284,3.045685,1.167513,0.870345,53.466080
117,Sambou Soumano,Lorient,fr Ligue 1,False,4,2,6,28,10,0.14,0.388350,0.194175,2.718447,0.970874,0.884124,53.075071
43,Karl Etta Eyong,Levante,es La Liga,False,6,2,8,41,21,0.15,0.382166,0.127389,2.611465,1.337580,0.989833,50.255468
40,Emersonn,Toulouse,fr Ligue 1,False,6,2,8,51,19,0.12,0.368098,0.122699,3.128834,1.165644,1.048974,48.804904
29,Keinan Davis,Udinese,it Serie A,False,10,3,13,45,22,0.13,0.476190,0.142857,2.142857,1.047619,1.059026,48.566644

In [191]:
# Rebuild striker dataset with reliability thresholds and per90 features

df = df[
    (df["MP"] >= 15) &
    (df["Min"] >= 900)
].copy()

strikers = df[df["Pos"] == "FW"].copy()

striker_features = ["Gls", "Ast", "G+A", "Sh", "SoT", "G/Sh"]

striker_data = strikers[
    [
        "Player",
        "Squad",
        "Comp",
        "MP",
        "Min",
        "90s",
        "is_ucl_team"
    ] + striker_features
].copy()

striker_data["Gls_per90"] = striker_data["Gls"] / striker_data["90s"]
striker_data["Ast_per90"] = striker_data["Ast"] / striker_data["90s"]
striker_data["Sh_per90"] = striker_data["Sh"] / striker_data["90s"]
striker_data["SoT_per90"] = striker_data["SoT"] / striker_data["90s"]

advanced_striker_features = [
    "Gls_per90",
    "Ast_per90",
    "Sh_per90",
    "SoT_per90",
    "G/Sh"
]

striker_data = striker_data.reset_index(drop=True)

X = striker_data[advanced_striker_features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = NearestNeighbors(
    n_neighbors=10,
    metric="euclidean"
)

model.fit(X_scaled)

striker_data.head()

,Player,Squad,Comp,MP,Min,90s,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90
0,Ragnar Ache,Köln,de Bundesliga,29,1718,19.1,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832
1,Akor Adams,Sevilla,es La Liga,28,1846,20.5,False,8,3,11,55,27,0.09,0.390244,0.146341,2.682927,1.317073
2,Che Adams,Torino,it Serie A,31,1826,20.3,False,5,2,7,48,14,0.10,0.246305,0.098522,2.364532,0.689655
3,Ludovic Ajorque,Brest,fr Ligue 1,29,2550,28.3,False,7,9,16,47,15,0.15,0.247350,0.318021,1.660777,0.530035
4,Alexandre Alemão,Rayo Vallecano,es La Liga,22,969,10.8,False,2,0,2,19,9,0.11,0.185185,0.000000,1.759259,0.833333

In [192]:
find_similar_non_ucl_players("Julián Álvarez", n_neighbors=15)

,Player,Squad,Comp,MP,Min,90s,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90,distance,similarity_score
0,Ragnar Ache,Köln,de Bundesliga,29,1718,19.1,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832,0.503260,66.522074
1,Akor Adams,Sevilla,es La Liga,28,1846,20.5,False,8,3,11,55,27,0.09,0.390244,0.146341,2.682927,1.317073,0.635584,61.140245
107,Rômulo,RB Leipzig,de Bundesliga,28,2080,23.1,False,9,4,13,61,27,0.15,0.389610,0.173160,2.640693,1.168831,0.732426,57.722507
73,Rafael Leão,Milan,it Serie A,27,1771,19.7,False,9,3,12,60,23,0.12,0.456853,0.152284,3.045685,1.167513,0.870345,53.466080
117,Sambou Soumano,Lorient,fr Ligue 1,30,931,10.3,False,4,2,6,28,10,0.14,0.388350,0.194175,2.718447,0.970874,0.884124,53.075071
43,Karl Etta Eyong,Levante,es La Liga,28,1410,15.7,False,6,2,8,41,21,0.15,0.382166,0.127389,2.611465,1.337580,0.989833,50.255468
40,Emersonn,Toulouse,fr Ligue 1,26,1469,16.3,False,6,2,8,51,19,0.12,0.368098,0.122699,3.128834,1.165644,1.048974,48.804904
29,Keinan Davis,Udinese,it Serie A,27,1890,21.0,False,10,3,13,45,22,0.13,0.476190,0.142857,2.142857,1.047619,1.059026,48.566644
96,Mikel Oyarzabal,Real Sociedad,es La Liga,30,2482,27.6,False,14,3,17,74,34,0.11,0.507246,0.108696,2.681159,1.231884,1.082570,48.017600
103,Andrea Pinamonti,Sassuolo,it Serie A,34,2434,27.0,False,8,3,11,70,27,0.11,0.296296,0.111111,2.592593,1.000000,1.113224,47.321055
104,Christian Pulisic,Milan,it Serie A,28,1549,17.2,False,8,3,11,50,24,0.16,0.465116,0.174419,2.906977,1.395349,1.150137,46.508658

In [193]:
import os
os.makedirs("../data/processed", exist_ok=True)

In [194]:
results = find_similar_non_ucl_players(
    "Julián Álvarez",
    n_neighbors=15
)

results.to_csv(
    "../data/processed/julian_alvarez_similar_non_ucl_strikers.csv",
    index=False
)

results

,Player,Squad,Comp,MP,Min,90s,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90,distance,similarity_score
0,Ragnar Ache,Köln,de Bundesliga,29,1718,19.1,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832,0.503260,66.522074
1,Akor Adams,Sevilla,es La Liga,28,1846,20.5,False,8,3,11,55,27,0.09,0.390244,0.146341,2.682927,1.317073,0.635584,61.140245
107,Rômulo,RB Leipzig,de Bundesliga,28,2080,23.1,False,9,4,13,61,27,0.15,0.389610,0.173160,2.640693,1.168831,0.732426,57.722507
73,Rafael Leão,Milan,it Serie A,27,1771,19.7,False,9,3,12,60,23,0.12,0.456853,0.152284,3.045685,1.167513,0.870345,53.466080
117,Sambou Soumano,Lorient,fr Ligue 1,30,931,10.3,False,4,2,6,28,10,0.14,0.388350,0.194175,2.718447,0.970874,0.884124,53.075071
43,Karl Etta Eyong,Levante,es La Liga,28,1410,15.7,False,6,2,8,41,21,0.15,0.382166,0.127389,2.611465,1.337580,0.989833,50.255468
40,Emersonn,Toulouse,fr Ligue 1,26,1469,16.3,False,6,2,8,51,19,0.12,0.368098,0.122699,3.128834,1.165644,1.048974,48.804904
29,Keinan Davis,Udinese,it Serie A,27,1890,21.0,False,10,3,13,45,22,0.13,0.476190,0.142857,2.142857,1.047619,1.059026,48.566644
96,Mikel Oyarzabal,Real Sociedad,es La Liga,30,2482,27.6,False,14,3,17,74,34,0.11,0.507246,0.108696,2.681159,1.231884,1.082570,48.017600
103,Andrea Pinamonti,Sassuolo,it Serie A,34,2434,27.0,False,8,3,11,70,27,0.11,0.296296,0.111111,2.592593,1.000000,1.113224,47.321055
104,Christian Pulisic,Milan,it Serie A,28,1549,17.2,False,8,3,11,50,24,0.16,0.465116,0.174419,2.906977,1.395349,1.150137,46.508658

In [195]:
# Example scouting report: Julián Álvarez benchmark

target_player = "Julián Álvarez"

results = find_similar_non_ucl_players(
    target_player,
    n_neighbors=15
)

results

,Player,Squad,Comp,MP,Min,90s,is_ucl_team,Gls,Ast,G+A,Sh,SoT,G/Sh,Gls_per90,Ast_per90,Sh_per90,SoT_per90,distance,similarity_score
0,Ragnar Ache,Köln,de Bundesliga,29,1718,19.1,False,7,4,11,52,22,0.13,0.366492,0.209424,2.722513,1.151832,0.503260,66.522074
1,Akor Adams,Sevilla,es La Liga,28,1846,20.5,False,8,3,11,55,27,0.09,0.390244,0.146341,2.682927,1.317073,0.635584,61.140245
107,Rômulo,RB Leipzig,de Bundesliga,28,2080,23.1,False,9,4,13,61,27,0.15,0.389610,0.173160,2.640693,1.168831,0.732426,57.722507
73,Rafael Leão,Milan,it Serie A,27,1771,19.7,False,9,3,12,60,23,0.12,0.456853,0.152284,3.045685,1.167513,0.870345,53.466080
117,Sambou Soumano,Lorient,fr Ligue 1,30,931,10.3,False,4,2,6,28,10,0.14,0.388350,0.194175,2.718447,0.970874,0.884124,53.075071
43,Karl Etta Eyong,Levante,es La Liga,28,1410,15.7,False,6,2,8,41,21,0.15,0.382166,0.127389,2.611465,1.337580,0.989833,50.255468
40,Emersonn,Toulouse,fr Ligue 1,26,1469,16.3,False,6,2,8,51,19,0.12,0.368098,0.122699,3.128834,1.165644,1.048974,48.804904
29,Keinan Davis,Udinese,it Serie A,27,1890,21.0,False,10,3,13,45,22,0.13,0.476190,0.142857,2.142857,1.047619,1.059026,48.566644
96,Mikel Oyarzabal,Real Sociedad,es La Liga,30,2482,27.6,False,14,3,17,74,34,0.11,0.507246,0.108696,2.681159,1.231884,1.082570,48.017600
103,Andrea Pinamonti,Sassuolo,it Serie A,34,2434,27.0,False,8,3,11,70,27,0.11,0.296296,0.111111,2.592593,1.000000,1.113224,47.321055
104,Christian Pulisic,Milan,it Serie A,28,1549,17.2,False,8,3,11,50,24,0.16,0.465116,0.174419,2.906977,1.395349,1.150137,46.508658

In [196]:
print(f"Scouting report based on: {target_player}")
print("Non-UCL players with similar striker profiles:")
results[["Player", "Squad", "Comp", "MP", "Min", "Gls", "Ast", "G+A", "similarity_score"]]

Scouting report based on: Julián Álvarez
Non-UCL players with similar striker profiles:

,Player,Squad,Comp,MP,Min,Gls,Ast,G+A,similarity_score
0,Ragnar Ache,Köln,de Bundesliga,29,1718,7,4,11,66.522074
1,Akor Adams,Sevilla,es La Liga,28,1846,8,3,11,61.140245
107,Rômulo,RB Leipzig,de Bundesliga,28,2080,9,4,13,57.722507
73,Rafael Leão,Milan,it Serie A,27,1771,9,3,12,53.466080
117,Sambou Soumano,Lorient,fr Ligue 1,30,931,4,2,6,53.075071
43,Karl Etta Eyong,Levante,es La Liga,28,1410,6,2,8,50.255468
40,Emersonn,Toulouse,fr Ligue 1,26,1469,6,2,8,48.804904
29,Keinan Davis,Udinese,it Serie A,27,1890,10,3,13,48.566644
96,Mikel Oyarzabal,Real Sociedad,es La Liga,30,2482,14,3,17,48.017600
103,Andrea Pinamonti,Sassuolo,it Serie A,34,2434,8,3,11,47.321055
104,Christian Pulisic,Milan,it Serie A,28,1549,8,3,11,46.508658

In [197]:
results.to_csv(
    "../data/processed/julian_alvarez_similar_non_ucl_strikers.csv",
    index=False
)